### ISSUE TITLE
SAKUROMAOG BE GRAYED OUT!!!

### ISSUE THREAD

**Issue by TonyBallOhKnee-Games** [TonyBallOhKnee-Games/fnf-baloney-engine#2]
![image](https://github.com/TonyBallOhKnee-Games/fnf-baloney-engine/assets/128426022/76772f1f-c784-46b9-9063-68a7aae0a033)
OG Sakuroma is greyed out even though she's in the list of characters to default unlock.

**Comment by TonyBallOhKnee-Games** [comment]
Also game crashes when exiting song.

**Comment by TonyBallOhKnee-Games** [comment]
> Also game crashes when exiting song.

never mind on this one (another mod just breaks it.)

**Comment by TorchTheDragon** [comment]
> ![image](https://private-user-images.githubusercontent.com/128426022/336614330-76772f1f-c784-46b9-9063-68a7aae0a033.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NDAyNTYsIm5iZiI6MTcxNzUzOTk1NiwicGF0aCI6Ii8xMjg0MjYwMjIvMzM2NjE0MzMwLTc2NzcyZjFmLWM3ODQtNDZiOS05MDYzLTY4YTdhYWUwYTAzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQyMjI1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjY1MmQwYzlkMTc4ZDRjOWQyMzE2MWQ1YTI2OTdkNmQyYjBjOTUxZGMyODQ3ZmI3ZGUwMDRlNDJkYjZkOWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J_4cf_ndDpreitW5PzNMG96O6HPBhVzQS5PA5bby2hY) OG Sakuroma is greyed out even though she's in the list of characters to default unlock.

Save data probably needs a bit of a reset, you can do that by just forcing it [here](https://github.com/TonyBallOhKnee-Games/fnf-baloney-engine/blob/main/source/torchsthings/TorchsCharMenuState.hx#L1283)

**Comment by TonyBallOhKnee-Games** [comment]
> > ![image](https://private-user-images.githubusercontent.com/128426022/336614330-76772f1f-c784-46b9-9063-68a7aae0a033.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NDAyNTYsIm5iZiI6MTcxNzUzOTk1NiwicGF0aCI6Ii8xMjg0MjYwMjIvMzM2NjE0MzMwLTc2NzcyZjFmLWM3ODQtNDZiOS05MDYzLTY4YTdhYWUwYTAzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQyMjI1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjY1MmQwYzlkMTc4ZDRjOWQyMzE2MWQ1YTI2OTdkNmQyYjBjOTUxZGMyODQ3ZmI3ZGUwMDRlNDJkYjZkOWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J_4cf_ndDpreitW5PzNMG96O6HPBhVzQS5PA5bby2hY) OG Sakuroma is greyed out even though she's in the list of characters to default unlock.
> 
> Save data probably needs a bit of a reset, you can do that by just forcing it [here](https://github.com/TonyBallOhKnee-Games/fnf-baloney-engine/blob/main/source/torchsthings/TorchsCharMenuState.hx#L1283)

thank
